version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: fastapi_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogapplication
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://user:userpassword@db:3306/blogapplication
    ports:
      - "8000:8000"

volumes:
  mysql_data:
